AllCops:
  Exclude:
    - apps/orders/rpc/*
    - apps/catalog/rpc/*
    - apps/accounts/rpc/*
    - apps/hello/rpc/*
    - Rakefile
    - db/migrations/*

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100

Style/FrozenStringLiteralComment:
  Exclude:
    - apps/orders/server.rb
    - apps/catalog/server.rb
    - apps/accounts/server.rb

Metrics/BlockLength:
  Exclude:
    - apps/api/application.rb
