version: '3.4'

x-app: &app
  build: .
  tty: true
  stdin_open: true
  volumes:
    - .:/app:cached

services:
  postgres:
    image: postgres:11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookshelf_development
    volumes:
      - postgres:/var/lib/postgresql/data

  graphql:
    <<: *app
    command: bundle exec hanami server --host=0.0.0.0
    entrypoint: './docker-entrypoint.sh'
    depends_on:
      - postgres
      - orders
      - catalog
    ports:
      - 2300:2300
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres/bookshelf_development
      ORDERS_URL: orders:50051
      CATALOG_URL: catalog:50051
      HANAMI_APPS: api

  orders:
    <<: *app
    command: bundle exec apps/orders/server.rb
    depends_on:
      - postgres
    expose:
      - 50051
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres/bookshelf_development

  catalog:
    <<: *app
    command: bundle exec apps/catalog/server.rb
    depends_on:
      - postgres
    expose:
      - 50051
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres/bookshelf_development

volumes:
  postgres:
