version: '3.4'

x-app: &app
  build: .
  tty: true
  stdin_open: true
  volumes:
    - .:/app:cached

services:
  postgres:
    image: postgres:11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookshelf_development
    volumes:
      - postgres:/var/lib/postgresql/data

  graphql:
    <<: *app
    command: bundle exec hanami server --host=0.0.0.0
    entrypoint: './docker-entrypoint.sh'
    depends_on:
      - postgres
    ports:
      - 2300:2300
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres/bookshelf_development"
      HANAMI_APPS: api

volumes:
  postgres:
