# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: apps/accounts/proto/accounts.proto for package 'accounts'

require 'grpc'
require 'apps/accounts/proto/accounts_pb'

module Accounts
  module AccountService
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'accounts.AccountService'

      rpc :PostAccount, PostAccountRequest, PostAccountResponse
      rpc :GetAccount, GetAccountRequest, GetAccountResponse
      rpc :GetAccounts, GetAccountsRequest, GetAccountsResponse
    end

    Stub = Service.rpc_stub_class
  end
end
