# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: apps/accounts/proto/accounts.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("apps/accounts/proto/accounts.proto", :syntax => :proto3) do
    add_message "accounts.Account" do
      optional :id, :string, 1
      optional :name, :string, 2
    end
    add_message "accounts.PostAccountRequest" do
      optional :name, :string, 1
    end
    add_message "accounts.PostAccountResponse" do
      optional :account, :message, 1, "accounts.Account"
    end
    add_message "accounts.GetAccountRequest" do
      optional :id, :string, 1
    end
    add_message "accounts.GetAccountResponse" do
      optional :account, :message, 1, "accounts.Account"
    end
    add_message "accounts.GetAccountsRequest" do
      optional :skip, :uint64, 1
      optional :take, :uint64, 2
    end
    add_message "accounts.GetAccountsResponse" do
      repeated :accounts, :message, 1, "accounts.Account"
    end
  end
end

module Accounts
  Account = Google::Protobuf::DescriptorPool.generated_pool.lookup("accounts.Account").msgclass
  PostAccountRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("accounts.PostAccountRequest").msgclass
  PostAccountResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("accounts.PostAccountResponse").msgclass
  GetAccountRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("accounts.GetAccountRequest").msgclass
  GetAccountResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("accounts.GetAccountResponse").msgclass
  GetAccountsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("accounts.GetAccountsRequest").msgclass
  GetAccountsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("accounts.GetAccountsResponse").msgclass
end
