# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: catalog.proto for package 'rpc'

require 'grpc'
require 'catalog_pb'

module Rpc
  module CatalogService
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'rpc.CatalogService'

      rpc :PostProduct, PostProductRequest, PostProductResponse
      rpc :GetProduct, GetProductRequest, GetProductResponse
      rpc :GetProducts, GetProductsRequest, GetProductsResponse
    end

    Stub = Service.rpc_stub_class
  end
end
