# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: catalog.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("catalog.proto", :syntax => :proto3) do
    add_message "rpc.Product" do
      optional :id, :string, 1
      optional :name, :string, 2
      optional :description, :string, 3
      optional :price, :double, 4
    end
    add_message "rpc.PostProductRequest" do
      optional :name, :string, 1
      optional :description, :string, 2
      optional :price, :double, 3
    end
    add_message "rpc.PostProductResponse" do
      optional :product, :message, 1, "rpc.Product"
    end
    add_message "rpc.GetProductRequest" do
      optional :id, :string, 1
    end
    add_message "rpc.GetProductResponse" do
      optional :product, :message, 1, "rpc.Product"
    end
    add_message "rpc.GetProductsRequest" do
      repeated :ids, :string, 3
    end
    add_message "rpc.GetProductsResponse" do
      repeated :products, :message, 1, "rpc.Product"
    end
  end
end

module Rpc
  Product = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.Product").msgclass
  PostProductRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.PostProductRequest").msgclass
  PostProductResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.PostProductResponse").msgclass
  GetProductRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.GetProductRequest").msgclass
  GetProductResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.GetProductResponse").msgclass
  GetProductsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.GetProductsRequest").msgclass
  GetProductsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.GetProductsResponse").msgclass
end
