# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orders.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("orders.proto", :syntax => :proto3) do
    add_message "rpc.Order" do
      optional :id, :string, 1
      optional :createdAt, :bytes, 2
      optional :accountId, :string, 3
      optional :totalPrice, :double, 4
      repeated :products, :message, 5, "rpc.Order.OrderProduct"
    end
    add_message "rpc.Order.OrderProduct" do
      optional :id, :string, 1
      optional :name, :string, 2
      optional :description, :string, 3
      optional :price, :double, 4
      optional :quantity, :uint32, 5
    end
    add_message "rpc.PostOrderRequest" do
      optional :accountId, :string, 2
      repeated :products, :message, 4, "rpc.PostOrderRequest.OrderProduct"
    end
    add_message "rpc.PostOrderRequest.OrderProduct" do
      optional :productId, :string, 2
      optional :quantity, :uint32, 3
    end
    add_message "rpc.PostOrderResponse" do
      optional :order, :message, 1, "rpc.Order"
    end
    add_message "rpc.GetOrderRequest" do
      optional :id, :string, 1
    end
    add_message "rpc.GetOrderResponse" do
      optional :order, :message, 1, "rpc.Order"
    end
    add_message "rpc.GetOrdersForAccountRequest" do
      optional :accountId, :string, 1
    end
    add_message "rpc.GetOrdersForAccountResponse" do
      repeated :orders, :message, 1, "rpc.Order"
    end
  end
end

module Rpc
  Order = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.Order").msgclass
  Order::OrderProduct = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.Order.OrderProduct").msgclass
  PostOrderRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.PostOrderRequest").msgclass
  PostOrderRequest::OrderProduct = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.PostOrderRequest.OrderProduct").msgclass
  PostOrderResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.PostOrderResponse").msgclass
  GetOrderRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.GetOrderRequest").msgclass
  GetOrderResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.GetOrderResponse").msgclass
  GetOrdersForAccountRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.GetOrdersForAccountRequest").msgclass
  GetOrdersForAccountResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.GetOrdersForAccountResponse").msgclass
end
