# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: hello.proto for package 'rpc'

require 'grpc'
require 'hello_pb'

module Rpc
  module HelloService
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'rpc.HelloService'

      rpc :sayHello, SayHelloRequest, SayHelloResponse
    end

    Stub = Service.rpc_stub_class
  end
end
