# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: accounts.proto for package 'rpc'

require 'grpc'
require 'accounts_pb'

module Rpc
  module AccountService
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'rpc.AccountService'

      rpc :PostAccount, PostAccountRequest, PostAccountResponse
      rpc :GetAccount, GetAccountRequest, GetAccountResponse
      rpc :GetAccounts, GetAccountsRequest, GetAccountsResponse
    end

    Stub = Service.rpc_stub_class
  end
end
