# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: accounts.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("accounts.proto", :syntax => :proto3) do
    add_message "rpc.Account" do
      optional :id, :string, 1
      optional :name, :string, 2
    end
    add_message "rpc.PostAccountRequest" do
      optional :name, :string, 1
    end
    add_message "rpc.PostAccountResponse" do
      optional :account, :message, 1, "rpc.Account"
    end
    add_message "rpc.GetAccountRequest" do
      optional :id, :string, 1
    end
    add_message "rpc.GetAccountResponse" do
      optional :account, :message, 1, "rpc.Account"
    end
    add_message "rpc.GetAccountsRequest" do
    end
    add_message "rpc.GetAccountsResponse" do
      repeated :accounts, :message, 1, "rpc.Account"
    end
  end
end

module Rpc
  Account = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.Account").msgclass
  PostAccountRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.PostAccountRequest").msgclass
  PostAccountResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.PostAccountResponse").msgclass
  GetAccountRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.GetAccountRequest").msgclass
  GetAccountResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.GetAccountResponse").msgclass
  GetAccountsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.GetAccountsRequest").msgclass
  GetAccountsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.GetAccountsResponse").msgclass
end
