# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: apps/orders/proto/orders.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("apps/orders/proto/orders.proto", :syntax => :proto3) do
    add_message "orders.Order" do
      optional :id, :string, 1
      optional :createdAt, :bytes, 2
      optional :accountId, :string, 3
      optional :totalPrice, :double, 4
      repeated :products, :message, 5, "orders.Order.OrderProduct"
    end
    add_message "orders.Order.OrderProduct" do
      optional :id, :string, 1
      optional :name, :string, 2
      optional :description, :string, 3
      optional :price, :double, 4
      optional :quantity, :uint32, 5
    end
    add_message "orders.PostOrderRequest" do
      optional :accountId, :string, 2
      repeated :products, :message, 4, "orders.PostOrderRequest.OrderProduct"
    end
    add_message "orders.PostOrderRequest.OrderProduct" do
      optional :productId, :string, 2
      optional :quantity, :uint32, 3
    end
    add_message "orders.PostOrderResponse" do
      optional :order, :message, 1, "orders.Order"
    end
    add_message "orders.GetOrderRequest" do
      optional :id, :string, 1
    end
    add_message "orders.GetOrderResponse" do
      optional :order, :message, 1, "orders.Order"
    end
    add_message "orders.GetOrdersForAccountRequest" do
      optional :accountId, :string, 1
    end
    add_message "orders.GetOrdersForAccountResponse" do
      repeated :orders, :message, 1, "orders.Order"
    end
    add_message "orders.HelloRequest" do
      optional :name, :string, 1
    end
    add_message "orders.HelloReply" do
      optional :message, :string, 1
    end
  end
end

module Orders
  Order = Google::Protobuf::DescriptorPool.generated_pool.lookup("orders.Order").msgclass
  Order::OrderProduct = Google::Protobuf::DescriptorPool.generated_pool.lookup("orders.Order.OrderProduct").msgclass
  PostOrderRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("orders.PostOrderRequest").msgclass
  PostOrderRequest::OrderProduct = Google::Protobuf::DescriptorPool.generated_pool.lookup("orders.PostOrderRequest.OrderProduct").msgclass
  PostOrderResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("orders.PostOrderResponse").msgclass
  GetOrderRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("orders.GetOrderRequest").msgclass
  GetOrderResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("orders.GetOrderResponse").msgclass
  GetOrdersForAccountRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("orders.GetOrdersForAccountRequest").msgclass
  GetOrdersForAccountResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("orders.GetOrdersForAccountResponse").msgclass
  HelloRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("orders.HelloRequest").msgclass
  HelloReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("orders.HelloReply").msgclass
end
