# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: apps/orders/proto/orders.proto for package 'orders'

require 'grpc'
require 'apps/orders/proto/orders_pb'

module Orders
  module OrdersService
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'orders.OrdersService'

      rpc :PostOrder, PostOrderRequest, PostOrderResponse
      rpc :GetOrdersForAccount, GetOrdersForAccountRequest, GetOrdersForAccountResponse
      rpc :SayHello, HelloRequest, HelloReply
    end

    Stub = Service.rpc_stub_class
  end
end
