# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: apps/catalog/proto/catalog.proto for package 'catalog'

require 'grpc'
require 'apps/catalog/proto/catalog_pb'

module Catalog
  module CatalogService
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'catalog.CatalogService'

      rpc :PostProduct, PostProductRequest, PostProductResponse
      rpc :GetProduct, GetProductRequest, GetProductResponse
      rpc :GetProducts, GetProductsRequest, GetProductsResponse
    end

    Stub = Service.rpc_stub_class
  end
end
